sudo: required

matrix:
  include:
    - dist: trusty
      language: python
      python: 3.6
      services:
        - docker
      script:
        - while sleep 300; do echo "=====[ $SECONDS seconds, still building... ]====="; done &
        - docker run --rm -it -v `pwd`:/io -w /io quay.io/pypa/manylinux1_x86_64 /io/manylinux.sh >> build.log 2>&1
        - ls dist/
        - kill %1
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      script:
        - git clone --depth=1 https://github.com/apache/rocketmq-client-cpp.git /tmp/rocketmq-client-cpp
        - while sleep 300; do echo "=====[ $SECONDS seconds, still building... ]====="; done &
        - cd /tmp/rocketmq-client-cpp && bash build.sh >> build.log 2>&1 && cd -
        - cp /tmp/rocketmq-client-cpp/bin/librocketmq.dylib rocketmq/
        - python3.6 setup.py bdist_wheel
        - ls dist/
        - kill %1

after_failure:
  - tail -n 2000 build.log

after_success:
  - |
    if [[ "${TRAVIS_TAG:-}" != "" ]]; then
      sudo pip3 install twine;
      twine upload --skip-existing dist/*;
    fi
