sudo: required

matrix:
  include:
    - dist: trusty
      services:
        - docker
      script:
        - travis_wait docker run --rm -it -v `pwd`:/io -w /io quay.io/pypa/manylinux1_x86_64 /io/manylinux.sh
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      script:
        - git clone --depth=1 https://github.com/apache/rocketmq-client-cpp.git /tmp/rocketmq-client-cpp
        - cp build_cpp.sh /tmp/rocketmq-client-cpp
        - cd /tmp/rocketmq-client-cpp && travis_wait bash build_cpp.sh && cd -
        - cp /tmp/rocketmq-client-cpp/bin/librocketmq.dylib rocketmq/
        - python3.6 setup.py bdist_wheel
