sudo: required
language: python

matrix:
  include:
    - dist: trusty
      services:
        - docker
      script:
        - while sleep 5m; do echo "=====[ $SECONDS seconds, still building... ]====="; done &
        - docker run --rm -it -v `pwd`:/io -w /io quay.io/pypa/manylinux1_x86_64 /io/manylinux.sh >> build.log 2>&1
        - kill %1
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      python: 3.6
      script:
        - git clone --depth=1 https://github.com/apache/rocketmq-client-cpp.git /tmp/rocketmq-client-cpp
        - while sleep 5m; do echo "=====[ $SECONDS seconds, still building... ]====="; done &
        - cd /tmp/rocketmq-client-cpp && bash build.sh >> build.log 2>&1 && cd -
        - cp /tmp/rocketmq-client-cpp/bin/librocketmq.dylib rocketmq/
        - python3.6 setup.py bdist_wheel
        - kill %1

after_failure:
  - tail -n 2000 build.log
